// backend/models/Report.js
import mongoose from "mongoose";

/**
 * Report Schema
 * --------------------------------------------------
 * Represents analytical or summary reports linked to cases
 * and generated by advocates, paralegals, mediators, or admins.
 *
 * Notes:
 * - `user` is the creator (owner) of the report.
 * - `metrics` caches useful numbers so the UI can load fast.
 * - Soft-delete implemented via `deletedAt`.
 */

const { Schema } = mongoose;

const reportSchema = new Schema(
  {
    /* Basic Info */
    title: {
      type: String,
      required: [true, "Report title is required"],
      trim: true,
      minlength: [3, "Title must be at least 3 characters long"],
      maxlength: [100, "Title cannot exceed 100 characters"],
    },

    description: {
      type: String,
      trim: true,
      maxlength: [2000, "Description cannot exceed 2000 characters"],
      default: "",
    },

    /* Related Case */
    case: {
      type: Schema.Types.ObjectId,
      ref: "Case",
      required: [true, "Associated case is required"],
      index: true,
    },

    /* Created By (User) */
    user: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: [true, "Report creator is required"],
      index: true,
    },

    /* Category */
    category: {
      type: String,
      enum: ["Performance", "Client Summary", "Case Overview", "Task Report", "Custom"],
      default: "Custom",
      index: true,
    },

    /* Optional metric cache for dashboard use */
    metrics: {
      totalCases: { type: Number, default: 0 },
      openTasks: { type: Number, default: 0 },
      overdueTasks: { type: Number, default: 0 },
      totalClients: { type: Number, default: 0 },
    },

    /* Soft delete flag */
    deletedAt: { type: Date, default: null, index: true },
  },
  {
    timestamps: true,
    versionKey: false,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

/* Indexes for performance */
reportSchema.index({ user: 1 });
reportSchema.index({ case: 1 });
reportSchema.index({ createdAt: -1 });
reportSchema.index({ category: 1 });
reportSchema.index({ deletedAt: 1 });

/* Virtuals */
reportSchema.virtual("durationSinceCreated").get(function () {
  if (!this.createdAt) return null;
  const diffMs = Date.now() - this.createdAt.getTime();
  const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
  return diffDays <= 0 ? "Today" : `${diffDays} day(s) ago`;
});

/* Middleware: tidy strings */
reportSchema.pre("save", function (next) {
  if (this.title) this.title = this.title.trim();
  if (this.description) this.description = this.description.trim();
  next();
});

/* Soft delete helpers */
reportSchema.methods.softDelete = async function (userId = null) {
  this.deletedAt = new Date();
  // optionally, push to history or audit log (not implemented here)
  await this.save();
  return this;
};

reportSchema.methods.restore = async function () {
  this.deletedAt = null;
  await this.save();
  return this;
};

const Report = mongoose.model("Report", reportSchema);
export default Report;
